### PR TITLE
consistent and proper handling of empty sets and missing queries

### LINKED ISSUE #2: calc_aggregate -c mode
I feel pretty strongly that TREC's `-c` mode (calculate over the set of queries in the qrels, not the intersection of the qrels and runs) should be the default. The current calc_aggregate operates _without_ this mode.

Does this need to be conditional? If so, where? As an argument of the measure or of calc_aggregate?

I think I'd rather have it non-conditional. If you want to score over a different set of queries, you should provide qrels without those queries to score.

### LINKED ISSUE #13: uniform handling of empty result sets
As reported here: https://github.com/terrier-org/pyterrier/issues/176

### PR DESCRIPTION
**Pull request by seanmacavaney**
This fixes #13 by making providers no longer throw errors when no qrels or runs are given.
 - If no qrels, nothing is yielded from `iter_calc` and `calc_aggregate` returns NaN for requested measures.
 - If no run, Metrics with values of 0 are returned for every measure-query combination that appeared in the requested measures and qrels. If there's also no qrels, nothing is yielded.

This also fixes #2, by also returning Metrics with values of 0 for any query that appeared in the qrels but not in the run.

### CODE REVIEW

**Comment by seanmacavaney** [comment]
@cmacdonald can you review this when you have a chance?

**Comment by cmacdonald** [comment]
We need to see how this behaves with PyTerrier? And check how it affects current release.

**Comment by seanmacavaney** [comment]
Are there any important test cases we should consider besides those already in the pyterrier unit tests? The original case affecting pyterrier was the empty result dataframe, which could probably use a test.

**Comment by cmacdonald** [comment]
So you have run the PyTerrier unit tests using this verison?

**Comment by seanmacavaney** [comment]
Not yet, but was considering whether what's there now would be adequate.

There's also the case of the set of the provided topics. `pt.Experiment` could be updated to (optionally?) filter the qrels down to only those that also appear in the provided topics. But that seems a bit beyond the scope of this PR.

**Comment by seanmacavaney** [comment]
Aside from the "expected" differences (where scores are now averaged over the full set of queries in the qrels) caught by pyterrier tests, this change breaks [pyterrier's `-c` detection](https://github.com/terrier-org/pyterrier/blob/master/pyterrier/pipelines.py#L313).

I propose that this detection could be moved to before the `for name, system in zip(names, retr_systems)` loop, and instead filter the qrels based on what appears in the topics. This functionality could be turned off with a new pt.Experiment parameter. Essentially:

```
if qid appears in qrels but not in topics:
    if full_qrels_mode:
        warn user that not all queries from qrels appear in topics
    else:
        remove qids from qrels that do not appear in topics
        if nothing remains in qrels:
            warn user that there was no overlap between topics and qrels -- this should be rare and is probably a user error
        else:
            warn user that qrels were removed based on what appears in the topics
```

Theoretically, we could also remove topics that do not appear in the qrels to save work -- they will not factor into the evaluation measures. But I do not think we should do this, as it will affect mrt. Perhaps there should be another warning in this case?

```
if qid appears in topics but not qrels:
    warn user that some topics appear in topics but not qrels
```

When used in conjunction with this PR, there would be the following changes to pyterrier's behaviour with default settings:
 - If a given query returns no results, it will now be counted against the system in terms of evaluation metrics. Currently, it is ignored and a warning is given to the user.
 - More comprehensive warnings are presented to users.

**Comment by cmacdonald** [comment]
PyTerrier already has another option that drops topics that dont have qrels, which is the _opposite_ of the proposal here (and is useful for MSMARCO at least). I think we can park this to a less busy time. Its likely that the integration and release of this will have to be aligned with a PyTerrier release.

**Comment by seanmacavaney** [comment]
fwiw- ir_datasets has `/judged` variants of collections when there are a lot of queries without judgments (e.g., in MS MARCO).

**Pull request merged**
